[package]
name = "assert_cfg"
version = "0.1.0"
edition = "2021"

[features]
# used in tests
foo = []
bar = []
baz = []
__test = ["foo", "bar", "baz"]

[dependencies.const_panic]
version = "0.2.0"
default-features = false

